---
- hosts: all 
  become: True
  tasks:
    - name: Install apache
      apt:
        name: "apache2"
        state: "present"
    - name: Start Apache server
      service:
        name: apache2
        state: restarted
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
